version: '3.8'

services:

  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    volumes:
      - static_volume:/home/app/static
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db